### ISSUE TITLE
ID of the parent VPC is not handled in the aws_subnet resource

### ISSUE THREAD

**Issue by AlexisNeveu** [ditrit/terrator-plugin#103]
**Describe the bug**

For a aws_subnet resource, when passing the id of the vpc it is not handled in the draw view.

**To Reproduce**

1. Go to text view
2. Write the code for the aws_subnet precising the vpc id.
3. Click on 'Draw'
4. See that the subnet is not drawn

**Expected behavior**

When the vpc id is passed to a subnet in the text view, this subnet should appear inside the vpc in the draw view

![Image](https://github.com/ditrit/terrator-plugin/assets/82414381/a8878dff-fbe5-441c-a067-856d23676fac)

**Screenshots**

![Image](https://github.com/ditrit/terrator-plugin/assets/82414381/0427fa63-6e89-4935-9255-8f124ab926b0)

![Image](https://github.com/ditrit/terrator-plugin/assets/82414381/21a6bca1-1956-4606-946f-610a5a15f6b7)

**Application (please complete the following information):**

- Terrator-plugin version 0.8.0

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Chrome
- Version:

**Comment by Zorin95670** [comment]
No more exists in 0.8.1
