### ISSUE TITLE
[Terraform] [AWS] count condition not handled

### ISSUE THREAD

**Issue by ihebsidhom** [ditrit/terrator-plugin#107]
**Describe the bug**

When we add a "count" condition, the ressouce should not be created when "count" value is 0.  

**To Reproduce**

1. Go to the text view
2. Add a any aws resource with a count condition
3. Switch to the draw view
4. See that the resource is successfully created

**Expected behavior**

The ressouce is created despite the count condition is 0.

Application (please complete the following information):

Terrator-plugin version 0.8.0
Desktop (please complete the following information):

OS: Windows 11
Browser: chrome
Version: 121.0.6167.161 (Build officiel) (64 bits)

**Comment by Zorin95670** [comment]
We add a box with number of element or ? when we can't say how many component have.
So I think job is done :)

Done in version of 0.10.0 of terrator
