### ISSUE TITLE
Missing definition on attribute

### ISSUE THREAD

**Issue by Rahzbob** [ditrit/terrator-plugin#67]
**Describe the bug**

If a component have an attribute.
It has no definition.

**To Reproduce**

Use the following Terraform code:
```terraform
resource "aws_elb" "aws_elb_1" {
    listener = {
        instance_port = "1"
    }
}
```

**Expected behavior**

Expect "listener" attribute to have a definition.

**Application (please complete the following information):**

- Terrator-plugin version [0.1.12]

**Comment by Zorin95670** [comment]
Resolved  in #68
