### ISSUE TITLE
Rendered format of Link attributes is incorrect

### ISSUE THREAD

**Issue by viennem** [ditrit/terrator-plugin#83]
**Describe the bug**

Link attributes are formatted like this by the renderer:

```terraform
resource "aws_security_group" "aws_security_group_1" {
    vpc_id = ["aws_vpc_1"]
}

resource "aws_vpc" "aws_vpc_1" {
}
```

but it is supposed to be like this:

```terraform
resource "aws_security_group" "aws_security_group_1" {
  vpc_id = aws_vpc.aws_vpc_1.id
}

resource "aws_vpc" "aws_vpc_1" {
}
```

* Example: https://registry.terraform.io/providers/hashicorp/aws/3.11.0/docs/resources/security_group#example-usage.

---

The general reference format for attributes of resources is: `<component_type>.<component_name>.<attribute_name>`

* The attribute name is mandatory.
   For most links, it will be `.id`, but it could be any other attribute name
   (see `aws_instance` -> `aws_security_group` example below).
* In most cases, the reference should not be an array (`[]`).
   There are exceptions (see `aws_instance` -> `aws_security_group` example below).
* Links to `data` resources should be prefixed with `data.`. Example: `data.aws_ami.ubuntu.id`.
   A reference can have multiple types of targets. For example, the `vpc_id` above could target either:
   * The `id` attribute of a `aws_vpc` resource: `aws_vpc = aws_vpc.aws_vpc_1.id`.
   * The `id` attribute of a `aws_vpc` data: `aws_vpc = data.aws_vpc.aws_vpc_1.id`.
   * A Terraform variable or locale: `aws_vpc = var.myVariable`/`local.myLocal`
   * A module output: `aws_vpc = module.myModule.myOutput`
   * An hardcoded value: `aws_vpc = "vpc-1a2b3c4d"`
   * ... -> Currently: `Link` attributes can only target a specific type of component.

---

`aws_instance` -> `aws_security_group` example:

```terraform
resource "aws_instance" "example" {
  ami           = "ami-abc123"
  instance_type = "t2.micro"

  security_groups = [
    aws_security_group.secgroup1.name,
    aws_security_group.secgroup2.name,
  ]
}

data "aws_security_group" "secgroup1" {
  id = 'sg-903004f8'
}

data "aws_security_group" "secgroup2" {
  id = 'sg-417217b9'
}
```

See the Terraform documentation for more details: https://developer.hashicorp.com/terraform/language/expressions/references.

---

**Application (please complete the following information):**

- `terrator-plugin` version `0.3.1`

**Comment by Zorin95670** [comment]
No more exists in 0.8.1
