### ISSUE TITLE
Variable file content set to null on render

### ISSUE THREAD

**Issue by k-y0u** [ditrit/terrator-plugin#98]
When rendering, variable files content is set to null even when the file had a proper content.

**Way to reproduce**
1. Go to Text view on Leto-Modelizer
2. Create a new file containing variables
3. Go to Draw view -> variables are displayed correctly in the Variables tab
4. Go back to Text view -> the file containing variables is missing

! Don't forget to uncomment #701 in DrawerEditor.feature in Leto-Modelizer

**Comment by Zorin95670** [comment]
No more exists in 0.8.1
